server:
  port: 8890
spring:
#redis配置
  redis:
        host: localhost
        port: 6379
        jedis:
          pool:
            max-active: 8
            max-idle: 500
            max-wait: -1
            min-idle: 0
        database: 0
#activeMQ配置
  activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
      pool:
        enabled: true
        max-connections: 50
        expiry-timeout: 10000
        idle-timeout: 30000
  http:
       multipart:
         max-file-size: 300Mb
         max-request-size: 300Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_cloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 300Mb
      max-request-size: 300Mb
logging:
  level:
    root: debug
    org.mybatis: debug
    com.bootdo: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: /mybatis/*.xml
pay:
  qr-code-url: http://xxx/waiter-login?activityCode=
